# Generated by Django 2.1 on 2018-08-30 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(default=teams.models.generate_invite_code, max_length=25)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'DECLINED'), (4, 'EXPIRED')], default=0)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team invitation',
                'verbose_name_plural': 'team invitations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together={('email', 'code')},
        ),
    ]
